// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Trace.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Trace.Localization.Language", typeof(Language).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string FillEveryField {
            get {
                return ResourceManager.GetString("FillEveryField", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        public static string UsernameRegisterConditions {
            get {
                return ResourceManager.GetString("UsernameRegisterConditions", resourceCulture);
            }
        }
        
        public static string PasswordRegisterConditions {
            get {
                return ResourceManager.GetString("PasswordRegisterConditions", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginWithGoogle", resourceCulture);
            }
        }
        
        public static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        public static string LocalIncorrectCredentialsWarning {
            get {
                return ResourceManager.GetString("LocalIncorrectCredentialsWarning", resourceCulture);
            }
        }
        
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        public static string OAuthError {
            get {
                return ResourceManager.GetString("OAuthError", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Rewards {
            get {
                return ResourceManager.GetString("Rewards", resourceCulture);
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string MyRoutes {
            get {
                return ResourceManager.GetString("MyRoutes", resourceCulture);
            }
        }
        
        public static string JoinACampaign {
            get {
                return ResourceManager.GetString("JoinACampaign", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        public static string CurrentActivityLabel {
            get {
                return ResourceManager.GetString("CurrentActivityLabel", resourceCulture);
            }
        }
        
        public static string MainActivityLabel {
            get {
                return ResourceManager.GetString("MainActivityLabel", resourceCulture);
            }
        }
        
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        public static string CaloriesLabel {
            get {
                return ResourceManager.GetString("CaloriesLabel", resourceCulture);
            }
        }
        
        public static string AvgSpeedLabel {
            get {
                return ResourceManager.GetString("AvgSpeedLabel", resourceCulture);
            }
        }
        
        public static string GetPositionError {
            get {
                return ResourceManager.GetString("GetPositionError", resourceCulture);
            }
        }
        
        public static string Challenges {
            get {
                return ResourceManager.GetString("Challenges", resourceCulture);
            }
        }
        
        public static string PullUpToUpdate {
            get {
                return ResourceManager.GetString("PullUpToUpdate", resourceCulture);
            }
        }
        
        public static string BikeCondition {
            get {
                return ResourceManager.GetString("BikeCondition", resourceCulture);
            }
        }
        
        public static string CycleToShop {
            get {
                return ResourceManager.GetString("CycleToShop", resourceCulture);
            }
        }
        
        public static string ErrorFetchingChallenges {
            get {
                return ResourceManager.GetString("ErrorFetchingChallenges", resourceCulture);
            }
        }
        
        public static string ChallengeWithoutCheckpointError {
            get {
                return ResourceManager.GetString("ChallengeWithoutCheckpointError", resourceCulture);
            }
        }
        
        public static string CheckpointDetails {
            get {
                return ResourceManager.GetString("CheckpointDetails", resourceCulture);
            }
        }
        
        public static string ShopOpenBetween {
            get {
                return ResourceManager.GetString("ShopOpenBetween", resourceCulture);
            }
        }
        
        public static string ShopAddress {
            get {
                return ResourceManager.GetString("ShopAddress", resourceCulture);
            }
        }
        
        public static string ShopPhoneNumber {
            get {
                return ResourceManager.GetString("ShopPhoneNumber", resourceCulture);
            }
        }
        
        public static string ShopWebsite {
            get {
                return ResourceManager.GetString("ShopWebsite", resourceCulture);
            }
        }
        
        public static string ShopDescription {
            get {
                return ResourceManager.GetString("ShopDescription", resourceCulture);
            }
        }
        
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        public static string Walking {
            get {
                return ResourceManager.GetString("Walking", resourceCulture);
            }
        }
        
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        public static string Cycling {
            get {
                return ResourceManager.GetString("Cycling", resourceCulture);
            }
        }
        
        public static string Driving {
            get {
                return ResourceManager.GetString("Driving", resourceCulture);
            }
        }
        
        public static string Stationary {
            get {
                return ResourceManager.GetString("Stationary", resourceCulture);
            }
        }
        
        public static string RoutesTracked {
            get {
                return ResourceManager.GetString("RoutesTracked", resourceCulture);
            }
        }
        
        public static string RewardsEarned {
            get {
                return ResourceManager.GetString("RewardsEarned", resourceCulture);
            }
        }
        
        public static string DistanceTravelledMeters {
            get {
                return ResourceManager.GetString("DistanceTravelledMeters", resourceCulture);
            }
        }
        
        public static string TimeSpentHours {
            get {
                return ResourceManager.GetString("TimeSpentHours", resourceCulture);
            }
        }
        
        public static string CaloriesBurnedKCals {
            get {
                return ResourceManager.GetString("CaloriesBurnedKCals", resourceCulture);
            }
        }
        
        public static string TodayStats {
            get {
                return ResourceManager.GetString("TodayStats", resourceCulture);
            }
        }
        
        public static string ThisWeekStats {
            get {
                return ResourceManager.GetString("ThisWeekStats", resourceCulture);
            }
        }
        
        public static string AllTimeStats {
            get {
                return ResourceManager.GetString("AllTimeStats", resourceCulture);
            }
        }
        
        public static string DistancePerActivity {
            get {
                return ResourceManager.GetString("DistancePerActivity", resourceCulture);
            }
        }
        
        public static string TimePerActivity {
            get {
                return ResourceManager.GetString("TimePerActivity", resourceCulture);
            }
        }
        
        public static string CaloriesPerActivity {
            get {
                return ResourceManager.GetString("CaloriesPerActivity", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string DateDetails {
            get {
                return ResourceManager.GetString("DateDetails", resourceCulture);
            }
        }
        
        public static string DurationDetails {
            get {
                return ResourceManager.GetString("DurationDetails", resourceCulture);
            }
        }
        
        public static string DistanceDetails {
            get {
                return ResourceManager.GetString("DistanceDetails", resourceCulture);
            }
        }
        
        public static string MostCommonActivityDetails {
            get {
                return ResourceManager.GetString("MostCommonActivityDetails", resourceCulture);
            }
        }
        
        public static string AvgSpeedDetails {
            get {
                return ResourceManager.GetString("AvgSpeedDetails", resourceCulture);
            }
        }
        
        public static string MaxSpeedDetails {
            get {
                return ResourceManager.GetString("MaxSpeedDetails", resourceCulture);
            }
        }
        
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        public static string CaloriesCalculation {
            get {
                return ResourceManager.GetString("CaloriesCalculation", resourceCulture);
            }
        }
        
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        public static string SearchRadius {
            get {
                return ResourceManager.GetString("SearchRadius", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        public static string Everything {
            get {
                return ResourceManager.GetString("Everything", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        public static string ToS {
            get {
                return ResourceManager.GetString("ToS", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string DeleteEverythingWarning {
            get {
                return ResourceManager.GetString("DeleteEverythingWarning", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string ServerConnectionError {
            get {
                return ResourceManager.GetString("ServerConnectionError", resourceCulture);
            }
        }
        
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        public static string NoCheckpointsFound {
            get {
                return ResourceManager.GetString("NoCheckpointsFound", resourceCulture);
            }
        }
        
        public static string OneCheckpointFound {
            get {
                return ResourceManager.GetString("OneCheckpointFound", resourceCulture);
            }
        }
        
        public static string ThereAre {
            get {
                return ResourceManager.GetString("ThereAre", resourceCulture);
            }
        }
        
        public static string CheckpointsNear {
            get {
                return ResourceManager.GetString("CheckpointsNear", resourceCulture);
            }
        }
        
        public static string NoRoutesYet {
            get {
                return ResourceManager.GetString("NoRoutesYet", resourceCulture);
            }
        }
        
        public static string OneRoute {
            get {
                return ResourceManager.GetString("OneRoute", resourceCulture);
            }
        }
        
        public static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
        
        public static string routes_ {
            get {
                return ResourceManager.GetString("routes.", resourceCulture);
            }
        }
        
        public static string OnlineLoginError {
            get {
                return ResourceManager.GetString("OnlineLoginError", resourceCulture);
            }
        }
        
        public static string RewardsUnlocked {
            get {
                return ResourceManager.GetString("RewardsUnlocked", resourceCulture);
            }
        }
        
        public static string RewardsUnlockedMessage {
            get {
                return ResourceManager.GetString("RewardsUnlockedMessage", resourceCulture);
            }
        }
        
        public static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        public static string NewCampaigns {
            get {
                return ResourceManager.GetString("NewCampaigns", resourceCulture);
            }
        }
        
        public static string CurrentCampaigns {
            get {
                return ResourceManager.GetString("CurrentCampaigns", resourceCulture);
            }
        }
        
        public static string NewCampaign {
            get {
                return ResourceManager.GetString("NewCampaign", resourceCulture);
            }
        }
        
        public static string FetchNewCampaign {
            get {
                return ResourceManager.GetString("FetchNewCampaign", resourceCulture);
            }
        }
        
        public static string NewCampaignMsg {
            get {
                return ResourceManager.GetString("NewCampaignMsg", resourceCulture);
            }
        }
        
        public static string YouHaveSubscribedTo {
            get {
                return ResourceManager.GetString("YouHaveSubscribedTo", resourceCulture);
            }
        }
        
        public static string UnsubscribeCampaign {
            get {
                return ResourceManager.GetString("UnsubscribeCampaign", resourceCulture);
            }
        }
        
        public static string UnsubscribeCampaignMsg {
            get {
                return ResourceManager.GetString("UnsubscribeCampaignMsg", resourceCulture);
            }
        }
        
        public static string YouHaveUnsubscribedFrom {
            get {
                return ResourceManager.GetString("YouHaveUnsubscribedFrom", resourceCulture);
            }
        }
        
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string AlreadySubscribedError {
            get {
                return ResourceManager.GetString("AlreadySubscribedError", resourceCulture);
            }
        }
        
        public static string NoRewardsYet {
            get {
                return ResourceManager.GetString("NoRewardsYet", resourceCulture);
            }
        }
        
        public static string OneRewardEarned {
            get {
                return ResourceManager.GetString("OneRewardEarned", resourceCulture);
            }
        }
        
        public static string ClaimReward {
            get {
                return ResourceManager.GetString("ClaimReward", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string TutorialDescription1 {
            get {
                return ResourceManager.GetString("TutorialDescription1", resourceCulture);
            }
        }
        
        public static string TutorialTitle2 {
            get {
                return ResourceManager.GetString("TutorialTitle2", resourceCulture);
            }
        }
        
        public static string TutorialDescription2 {
            get {
                return ResourceManager.GetString("TutorialDescription2", resourceCulture);
            }
        }
        
        public static string TutorialTitle3 {
            get {
                return ResourceManager.GetString("TutorialTitle3", resourceCulture);
            }
        }
        
        public static string TutorialDescription3 {
            get {
                return ResourceManager.GetString("TutorialDescription3", resourceCulture);
            }
        }
        
        public static string TutorialTitle4 {
            get {
                return ResourceManager.GetString("TutorialTitle4", resourceCulture);
            }
        }
        
        public static string TutorialDescription4 {
            get {
                return ResourceManager.GetString("TutorialDescription4", resourceCulture);
            }
        }
        
        public static string GotIt {
            get {
                return ResourceManager.GetString("GotIt", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyPart1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPart1", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyPart2 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPart2", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyPart3 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPart3", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyPart4 {
            get {
                return ResourceManager.GetString("PrivacyPolicyPart4", resourceCulture);
            }
        }
        
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        public static string IneligibleBackground {
            get {
                return ResourceManager.GetString("IneligibleBackground", resourceCulture);
            }
        }
        
        public static string EligibleBackground {
            get {
                return ResourceManager.GetString("EligibleBackground", resourceCulture);
            }
        }
        
        public static string IneligibleWarning {
            get {
                return ResourceManager.GetString("IneligibleWarning", resourceCulture);
            }
        }
        
        public static string EligibleWarning {
            get {
                return ResourceManager.GetString("EligibleWarning", resourceCulture);
            }
        }
        
        public static string YouHaveEarned {
            get {
                return ResourceManager.GetString("YouHaveEarned", resourceCulture);
            }
        }
        
        public static string nRewardsClickToSeeWhat {
            get {
                return ResourceManager.GetString("nRewardsClickToSeeWhat", resourceCulture);
            }
        }
        
        public static string IAgreeToToS {
            get {
                return ResourceManager.GetString("IAgreeToToS", resourceCulture);
            }
        }
        
        public static string ToSUncheckedError {
            get {
                return ResourceManager.GetString("ToSUncheckedError", resourceCulture);
            }
        }
        
        public static string PullUpToGetLocalCampaign {
            get {
                return ResourceManager.GetString("PullUpToGetLocalCampaign", resourceCulture);
            }
        }
        
        public static string YouEarn {
            get {
                return ResourceManager.GetString("YouEarn", resourceCulture);
            }
        }
        
        public static string RewardClaimedAt {
            get {
                return ResourceManager.GetString("RewardClaimedAt", resourceCulture);
            }
        }
        
        public static string RewardEarnedAt {
            get {
                return ResourceManager.GetString("RewardEarnedAt", resourceCulture);
            }
        }
        
        public static string RewardAlreadyClaimedError {
            get {
                return ResourceManager.GetString("RewardAlreadyClaimedError", resourceCulture);
            }
        }
        
        public static string TrajectoryNotUploadedError {
            get {
                return ResourceManager.GetString("TrajectoryNotUploadedError", resourceCulture);
            }
        }
        
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        public static string BiklioWelcomeMessage {
            get {
                return ResourceManager.GetString("BiklioWelcomeMessage", resourceCulture);
            }
        }
        
        public static string BiklioAudioWarningMessage {
            get {
                return ResourceManager.GetString("BiklioAudioWarningMessage", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        public static string StartTracking {
            get {
                return ResourceManager.GetString("StartTracking", resourceCulture);
            }
        }
        
        public static string DisableBackgroundAudio {
            get {
                return ResourceManager.GetString("DisableBackgroundAudio", resourceCulture);
            }
        }
        
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        public static string DoNotAllow {
            get {
                return ResourceManager.GetString("DoNotAllow", resourceCulture);
            }
        }
    }
}
